database: T2VQA
model: aveScore
feat_len: 8
split: 1
epochs: 30
save_model: True

# data config
mos_file: /home/user/Documents/vqadata/BVQAdata/T2VQA.csv
prompt_num: 468
imgs_dir: /home/user/Documents/vqadata/BVQAdata/T2VQA_frames
tem_feat_dir: /home/user/Documents/vqadata/BVQAdata/T2VQA_tem
spa_feat_dir: /home/user/Documents/vqadata/BVQAdata/T2VQA_spa


# model config
lr: !!float 5e-6
decay_ratio: !!float 0.9
decay_interval: 2
print_samples: 2000
train_batch_size: 8
num_workers: 16
loss_type: plcc


resize: 256
crop_size: 224

pretrained_weights: none

        
        